clc;clear;
f=figure;
f.WindowState="Maximized";
plotHandles_1=getPlotHandles(2,2,[0.08 0.08 0.73 0.9],0.25,0.06,0);
plotHandles_2=getPlotHandles(2,2,[0.38 0.08 0.6 0.9],0.38,0.06,0);
plot_conn("PLV", plotHandles_1,plotHandles_2,1);
plot_conn("WPLI", plotHandles_1,plotHandles_2,2);
set_axis_ticks_fontsize(plotHandles_1,22,16,1);
set_axis_ticks_fontsize(plotHandles_1,22,16,2);
set_axis_ticks_fontsize(plotHandles_2,22,16,1);
set_axis_ticks_fontsize(plotHandles_2,22,16,2);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
labels = {'A','B','C','D','E','F','G','H'};
x_positions = [0.03,0.33, 0.52, 0.82];
y_positions = [0.88, 0.41];  % top and bottom rows
k = 1;
for j = 1:length(y_positions)
    for i = 1:length(x_positions)
        annotation('textbox', ...
            [x_positions(i), y_positions(j), 0.1, 0.1], ...
            'String', labels{k}, ...
            'FontSize', 28, ...
            'FontWeight', 'Bold', ...
            'EdgeColor', 'none', ...
            'FontName', 'Helvetica');
        k = k + 1;
    end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
annotation('textbox',...
    [0.05 0.68 0.08 0.09],...
    'String',{'Monkey 1'},...
    'Rotation',90,...
    'FontWeight','bold',...
    'FontSize',20,...
    'FontName','Helvetica',...
    'EdgeColor',[1 1 1]);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
annotation('textbox',...
    [0.05 0.21 0.08 0.09],...
    'String',{'Monkey 2'},...
    'Rotation',90,...
    'FontWeight','bold',...
    'FontSize',20,...
    'FontName','Helvetica',...
    'EdgeColor',[1 1 1]);